const menuData = {
    food: [
        {
            id: 'f1',
            name: 'Koshari',
            category: 'meal',
            price: 55,
            description: 'Rice, lentils, pasta, chickpeas, crispy onions & spicy tomato sauce',
            image: 'assets/images/koshari.jpg',
            hunger: 'feast',
            flavor: ['savory', 'spicy', 'tangy', 'bold', 'comforting'],
            protein: ['vegetarian', 'carb-heavy'],
            texture: ['crispy', 'crunchy', 'hearty', 'chewy', 'layered', 'complex'],
            occasion: ['lunch', 'dinner', 'traditional', 'comfort']
        },
        {
            id: 'f2',
            name: 'Molokhia with Chicken',
            category: 'meal',
            price: 120,
            description: 'Jute leaves stew with garlic, coriander & tender chicken',
            image: 'assets/images/molokhia.jpg',
            hunger: 'normal',
            flavor: ['savory', 'rich', 'herbaceous', 'fresh', 'comforting'],
            protein: ['chicken'],
            texture: ['soft', 'tender'],
            occasion: ['dinner', 'traditional', 'comfort']
        },
        {
            id: 'f3',
            name: 'Ful Medames',
            category: 'meal',
            price: 35,
            description: 'Slow-cooked fava beans with olive oil, lemon & cumin',
            image: 'assets/images/ful.jpg',
            hunger: 'light',
            flavor: ['savory', 'mild', 'comforting'],
            protein: ['vegetarian', 'carb-heavy'],
            texture: ['soft', 'hearty', 'tender'],
            occasion: ['lunch', 'traditional']
        },
        {
            id: 'f4',
            name: 'Hawawshi',
            category: 'meal',
            price: 70,
            description: 'Egyptian spiced minced meat baked in pita bread',
            image: 'assets/images/hawawshi.jpg',
            hunger: 'normal',
            flavor: ['savory', 'spicy', 'bold', 'rich'],
            protein: ['beef'],
            texture: ['crispy', 'crunchy', 'hearty'],
            occasion: ['lunch', 'dinner']
        },
        {
            id: 'f5',
            name: 'Mahshi Warak Enab',
            category: 'meal',
            price: 90,
            description: 'Stuffed grape leaves with rice, herbs & spices',
            image: 'assets/images/mahshi.jpg',
            hunger: 'light',
            flavor: ['savory', 'tangy', 'zesty', 'herbaceous'],
            protein: ['vegetarian', 'carb-heavy'],
            texture: ['soft', 'tender'],
            occasion: ['dinner', 'celebration']
        },
        {
            id: 'f6',
            name: 'Fatta',
            category: 'meal',
            price: 110,
            description: 'Layers of rice, crispy bread, garlic vinegar sauce & beef',
            image: 'assets/images/fatta.jpg',
            hunger: 'feast',
            flavor: ['savory', 'rich', 'tangy', 'zesty', 'comforting'],
            protein: ['beef', 'carb-heavy'],
            texture: ['layered', 'complex', 'soft', 'hearty'],
            occasion: ['dinner', 'traditional', 'celebration']
        }
    ],
    drinks: [
        {
            id: 'd1',
            name: 'Sahlab',
            category: 'drink',
            price: 40,
            description: 'Hot milk, orchid root, cinnamon, coconut & nuts',
            image: 'assets/images/sahlab.jpg',
            temp: ['hot'],
            flavor: ['sweet', 'creamy', 'floral', 'rich', 'spiced'],
            purpose: ['calm', 'indulge'],
            thickness: 'thick',
            adventure: 'classic'
        },
        {
            id: 'd2',
            name: 'Karkadeh',
            category: 'drink',
            price: 25,
            description: 'Dried hibiscus petals, sugar, lemon — hot or cold',
            image: 'assets/images/karkadeh.jpg',
            temp: ['hot', 'cold'],
            flavor: ['tangy', 'fruity'],
            purpose: ['refresh', 'calm'],
            thickness: 'light',
            adventure: 'classic'
        },
        {
            id: 'd3',
            name: 'Sobia',
            category: 'drink',
            price: 30,
            description: 'Coconut milk, rice, sugar, vanilla — chilled',
            image: 'assets/images/sobia.jpg',
            temp: ['cold'],
            flavor: ['sweet', 'creamy', 'rich'],
            purpose: ['refresh', 'indulge'],
            thickness: 'medium',
            adventure: 'classic'
        },
        {
            id: 'd4',
            name: 'Mango Asab',
            category: 'drink',
            price: 35,
            description: 'Fresh sugarcane juice blended with mango pulp',
            image: 'assets/images/mango-asab.jpg',
            temp: ['cold'],
            flavor: ['sweet', 'fruity', 'tangy'],
            purpose: ['energize', 'refresh'],
            thickness: 'medium',
            adventure: 'bold'
        },
        {
            id: 'd5',
            name: 'Yansoon',
            category: 'drink',
            price: 20,
            description: 'Anise seeds, honey, lemon zest',
            image: 'assets/images/yansoon.jpg',
            temp: ['hot'],
            flavor: ['earthy', 'herbal', 'floral', 'aromatic'],
            purpose: ['calm', 'digestion'],
            thickness: 'light',
            adventure: 'balanced'
        },
        {
            id: 'd6',
            name: 'Tamr Hindi',
            category: 'drink',
            price: 28,
            description: 'Tamarind pulp, sugar, rose water, ice',
            image: 'assets/images/tamr-hindi.jpg',
            temp: ['cold'],
            flavor: ['tangy', 'fruity', 'sweet'],
            purpose: ['refresh', 'digestion'],
            thickness: 'light',
            adventure: 'balanced'
        }
    ],
    desserts: [
        {
            id: 'ds1',
            name: 'Om Ali',
            category: 'dessert',
            price: 60,
            description: 'Puff pastry, milk, nuts, raisins, coconut, cinnamon',
            image: 'assets/images/om-ali.jpg',
            sweetness: 'very',
            temp: ['hot'],
            texture: ['soft', 'creamy', 'cake'],
            family: ['pastry', 'dough', 'milk', 'dairy', 'nut'],
            weight: 'rich'
        },
        {
            id: 'ds2',
            name: 'Basbousa',
            category: 'dessert',
            price: 40,
            description: 'Semolina cake, syrup, coconut, almonds',
            image: 'assets/images/basbousa.jpg',
            sweetness: 'very',
            temp: ['hot', 'cold', 'room'],
            texture: ['soft', 'syrupy', 'sticky', 'cake'],
            family: ['pastry', 'dough', 'nut', 'grain'],
            weight: 'rich'
        },
        {
            id: 'ds3',
            name: 'Konafa with Cream',
            category: 'dessert',
            price: 75,
            description: 'Shredded phyllo, cream, pistachios, syrup',
            image: 'assets/images/konafa.jpg',
            sweetness: 'very',
            temp: ['hot', 'cold', 'room'],
            texture: ['crunchy', 'crispy', 'creamy', 'smooth', 'syrupy'],
            family: ['pastry', 'dough', 'milk', 'dairy', 'nut'],
            weight: 'rich'
        },
        {
            id: 'ds4',
            name: 'Mahalabia',
            category: 'dessert',
            price: 35,
            description: 'Milk pudding with rose water, pistachios',
            image: 'assets/images/mahalabia.jpg',
            sweetness: 'lightly',
            temp: ['cold'],
            texture: ['creamy', 'smooth'],
            family: ['milk', 'dairy', 'nut'],
            weight: 'light'
        },
        {
            id: 'ds5',
            name: 'Zalabia',
            category: 'dessert',
            price: 30,
            description: 'Fried dough balls in honey syrup',
            image: 'assets/images/zalabia.jpg',
            sweetness: 'very',
            temp: ['hot', 'room'],
            texture: ['crunchy', 'crispy', 'syrupy', 'sticky'],
            family: ['fried', 'dough', 'pastry'],
            weight: 'balanced'
        },
        {
            id: 'ds6',
            name: 'Roz bel Laban',
            category: 'dessert',
            price: 45,
            description: 'Egyptian rice pudding with cinnamon',
            image: 'assets/images/roz-bel-laban.jpg',
            sweetness: 'moderately',
            temp: ['cold'],
            texture: ['creamy', 'smooth', 'soft'],
            family: ['milk', 'dairy', 'grain'],
            weight: 'balanced'
        }
    ]
};
